### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by atc0005** [atc0005/list-emails#22]
Received this error report via local ticket, svn-1238:

```
2020-09-09 16:19:26,406 - get_email_subject_lines - Searching "Inbox" for ALL messages
Traceback (most recent call last):
File "C:\Users\Public\Documents\PLACEHOLDER\list_emails.py", line 468, in <module>
account, mailbox, folder)
File "C:\Users\Public\Documents\PLACEHOLDER\list_emails.py", line 330, in get_email_subject_lines
subject = subject.replace('Subject:', '').strip()
AttributeError: 'NoneType' object has no attribute 'replace'
```

Line (not a 1:1 match due to local changes):

https://github.com/atc0005/list-emails/blob/b794948d52ee44c57af9cd02b58f88ffa3d7c0eb/list_emails.py#L327

Applicable code:

https://github.com/atc0005/list-emails/blob/b794948d52ee44c57af9cd02b58f88ffa3d7c0eb/list_emails.py#L299-L329

**Comment by atc0005** [comment]
https://support.esri.com/en/technical-article/000014467
