### ISSUE TITLE
imaplib.IMAP4.error: command CLOSE illegal in state AUTH, only allowed in states SELECTED

### ISSUE THREAD

**Issue by atc0005** [atc0005/list-emails#25]
Log output:

```console
2020-09-14 08:41:35,417 - <module> - Checking folders for account1
2020-09-14 08:41:36,213 - <module> - Examining "Inbox" folder for messages ...
2020-09-14 08:41:36,320 - <module> - 0 messages in "Inbox" folder
2020-09-14 08:41:36,320 - <module> - Finished examining "Inbox" folder for messages.
2020-09-14 08:41:36,321 - <module> - Examining "Junk EMail" folder for messages ...
2020-09-14 08:41:36,371 - <module> - 0 messages in "Junk EMail" folder
2020-09-14 08:41:36,371 - <module> - Finished examining "Junk EMail" folder for messages.
2020-09-14 08:41:36,372 - <module> - Examining "Trash" folder for messages ...
2020-09-14 08:41:36,436 - <module> - account1: Unable to list messages in the "Trash" folder: [b"Trash doesn't exist."]
2020-09-14 08:41:36,436 - <module> - Finished examining "Trash" folder for messages.
2020-09-14 08:41:36,437 - <module> - Unable to close mailbox for account1 (command CLOSE illegal in state AUTH, only allowed in states SELECTED)
Traceback (most recent call last):
  File "list_emails.py", line 505, in <module>
    mailbox.close()
  File "C:\Program Files\Python37\lib\imaplib.py", line 461, in close
    typ, dat = self._simple_command('CLOSE')
  File "C:\Program Files\Python37\lib\imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Program Files\Python37\lib\imaplib.py", line 944, in _command
    ', '.join(Commands[name])))
imaplib.IMAP4.error: command CLOSE illegal in state AUTH, only allowed in states SELECTED
```

Config file:

```ini
# accounts.ini file located in the same directory as the `list_emails.py` script

[account1]

username = account1@example.com
password = PlaceholderPassword

# Here is an example of three folders that need to be checked. The last folder
# is found beneath the Inbox folder on the account. That hierarchy is
# denoted here by naming the Inbox folder followed by a slash and then the
# subfolder name.
folders = "Inbox", "Junk EMail", "Trash"
```

**Comment by atc0005** [comment]
Two lines that stand out:

```log
2020-09-14 08:41:36,436 - <module> - account1: Unable to list messages in the "Trash" folder: [b"Trash doesn't exist."]

2020-09-14 08:41:36,437 - <module> - Unable to close mailbox for account1 (command CLOSE illegal in state AUTH, only allowed in states SELECTED)
```

In this case, the `Trash` folder did not exist, so modifying the config file to omit that non-existent mailbox was a valid workaround. Ultimately, better error handling should allow non-existent mailboxes to be handled in a cleaner way.

Maybe failing the task is still desirable, but the exception information should be muted and a human readable error provided in its place.

```ini
# accounts.ini file located in the same directory as the `list_emails.py` script

[account1]

username = account1@example.com
password = PlaceholderPassword

# Here is an example of three folders that need to be checked. The last folder
# is found beneath the Inbox folder on the account. That hierarchy is
# denoted here by naming the Inbox folder followed by a slash and then the
# subfolder name.
folders = "Inbox", "Junk EMail"
```

**Comment by atc0005** [comment]
See also the workaround applied [here](https://github.com/gwasser/django-helpdesk/commit/96cae9bdd5132d5a4468d9d18c647bd2431e9f03). 

They opted to perform a search on their `server` object (what we're calling `mailbox`) wrapped within a `try/except` block to help detect misnamed/missing "folders".
