### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u231a' in position 144: character maps to <undefined>

### ISSUE THREAD

**Issue by atc0005** [atc0005/list-emails#7]
The following issue was reported today:

```
--- Logging error ---
Traceback (most recent call last):
File "C:\Program Files\Python37\lib\logging\__init__.py", line 985, in emit
stream.write(msg)
File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u231a' in position 153: character maps to <undefined>
Call stack:
File "C:\Users\Public\Documents\USERNAME\list_emails.py", line 490, in <module>
account, mailbox, folder)
File "C:\Users\Public\Documents\USERNAME\list_emails.py", line 356, in get_email_subject_lines
subject, type(subject))
Message: 'Type of r after decoding passes: %s'
Arguments: ('Just a few hours left to get 30 off WooCommerce.com\xa0⌚', <class 'str'>)
--- Logging error ---
Traceback (most recent call last):
File "C:\Program Files\Python37\lib\logging\__init__.py", line 985, in emit
stream.write(msg)
File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u231a' in position 144: character maps to <undefined>
Call stack:
File "C:\Users\Public\Documents\USERNAME\list_emails.py", line 501, in <module>
TIMESTAMP)
File "C:\Users\Public\Documents\USERNAME\list_emails.py", line 395, in record_emails
log.debug("Writing: r of type %s", line, type(line))
Message: 'Writing: %r of type %s'
Arguments: ('Just a few hours left to get 30 off WooCommerce.com\xa0', <class 'str'>)
Traceback (most recent call last):
File "C:\Users\Public\Documents\USERNAME\list_emails.py", line 501, in <module>
TIMESTAMP)
File "C:\Users\Public\Documents\USERNAME\list_emails.py", line 396, in record_emails
output_fh.write(line + '\n')
File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u231a' in position 53: character maps to <undefined>
```

I've not dug into this to see what I'm doing wrong. I'm going to guess that at some point I attempt to convert Unicode to standard ASCII, thus the encoding error.

**Comment by atc0005** [comment]
https://stackoverflow.com/questions/14630288/unicodeencodeerror-charmap-codec-cant-encode-character-maps-to-undefined

**Comment by atc0005** [comment]
https://docs.python.org/3/library/email.header.html

**Comment by atc0005** [comment]
I can't seem to reproduce the crash on any of my test systems, but I was able to consistently reproduce a bug where emails with Unicode characters in the Subject line were not recorded in the output file. They were found in an earlier debug count for all messages in the inbox, so something is obviously off.

**Comment by atc0005** [comment]
https://stackoverflow.com/questions/10706547/add-encoding-parameter-to-logging-basicconfig

**Comment by atc0005** [comment]
https://docs.python.org/3/howto/unicode.html
